#!/usr/bin/env bash

# DilwarBot - ALONExOPxMUSIC

# Copyright (C) 2021-2022 TeamVenom

#

# This file is a part of < https://github.com/DilwarBot/ALONExOPxMUSIC/ >

# PLease read the GNU Affero General Public License in <https://www.github.com/DilwarBot/ALONExOPxMUSIC/LICENSE/>.

if [ -d "resources" ]

then

    echo "Current directory Identified.."

else

    apt install git -y

    git clone https://github.com/DilwarBot/ALONExOPxMUSIC

    cd ALONExOPxMUSIC

fi

bash resources/startup/termux.sh
